version: "3.8"
services:
  test-db:
    image: cgi-rag:latest
    restart: always
    environment:
      POSTGRES_DB: rag
      POSTGRES_USER: superuser
      POSTGRES_PASSWORD: password
    volumes:
      - ./scripts/db/init/sql:/docker-entrypoint-initdb.d/
    ports:
      - "1996:5432"
