"""embedding

Revision ID: 744e9f5c1239
Revises: 197e2ddf183c
Create Date: 2024-07-01 11:04:27.068313

"""

from alembic import op
import sqlalchemy as sa
import pgvector

# revision identifiers, used by Alembic.
revision = "744e9f5c1239"
down_revision = "197e2ddf183c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text("CREATE  EXTENSION IF NOT EXISTS vector;"))
    op.create_table(
        "embedding",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False
        ),
        sa.Column("content", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_embeddings")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("embedding")
    # ### end Alembic commands ###
